#server:
#  port: 8082
#spring:
#  datasource:
#    password: password
#    url: jdbc:mysql://localhost:3306/HR-Department
#    username: root
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true